Change all tokens link to engine by REST controllers
inventorsoft-academy/geek-school pull request #19
Opened 2019-07-10 20:08 UTC by ifochka9519

Improve code. Change all ModelAndView Controllers to REST Controllers

2019-07-15 19:52 UTC, inventorsoft-academy requested changes

2019-07-15 19:52 UTC, inventorsoft-academy commented on src/main/resources/templates/invitations/form.html
> +            type: "get",
why get?

2019-07-15 19:52 UTC, inventorsoft-academy commented on src/main/resources/templates/invitations/form.html
>              url: "/api/users/users/user",
/users is duplicated

2019-07-15 19:52 UTC, inventorsoft-academy commented on src/main/resources/templates/passwords/forgotPassword.html
>  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
replace with local version

2019-07-15 19:55 UTC, merged

2019-07-17 00:55 UTC, ifochka9519 commented on src/main/resources/templates/invitations/form.html
> +            type: "get",
I doubted what right, I'll change.

2019-07-17 00:55 UTC, ifochka9519 commented on src/main/resources/templates/invitations/form.html
>              url: "/api/users/users/user",
I'll fix!

2019-07-17 00:56 UTC, ifochka9519 commented on src/main/resources/templates/passwords/forgotPassword.html
>  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
Ok!