User controller
inventorsoft-academy/geek-school pull request #8
Opened 2019-06-24 10:05 UTC by Fedia23

Added user pages

2019-06-26 06:00 UTC, inventorsoft-academy requested changes

2019-06-26 06:00 UTC, inventorsoft-academy commented on src/main/java/com/geekschool/config/security/ApplicationSecurity.java
> +                    .csrf().disable();
Why do we disable CSRF?

2019-06-26 06:00 UTC, inventorsoft-academy commented on src/main/java/com/geekschool/controllers/UserController.java
> +        UserMapper userMapper = new UserMapper(user);
Can we make this user mapper as spring component, pass the user inside `convertToUserDto` and inject it?

2019-06-26 06:00 UTC, inventorsoft-academy commented on src/main/java/com/geekschool/mapper/MessageMapper.java
> +public class MessageMapper {
Please, make it as spring bean and use dependency injection

2019-06-26 06:00 UTC, inventorsoft-academy commented on src/main/java/com/geekschool/mapper/UserMapper.java
> +public class UserMapper {
See comments above

2019-06-26 06:00 UTC, inventorsoft-academy commented on src/main/java/com/geekschool/service/UserService.java
> +import com.geekschool.constants.Status;
Please, get rid from this interface

2019-06-26 06:00 UTC, inventorsoft-academy commented on src/main/java/com/geekschool/service/impl/UserServiceImpl.java
>          User user = userRepository.findById(id).get();
This invocation might result with NullPointerException, but we want to avoid it by using `Optional`. Consider, using `orElseThrow` method to terminate process early and choose corresponding exception (See org.springframework.web.server.ResponseStatusException).

Also, you can use composition capabilities of `Optional` and rewrite this in more elegant way:
`userRepository.findById(id).map(user -> new UserMapper(user). convertToUserDto()).orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND));`

2019-06-26 06:00 UTC, inventorsoft-academy commented on src/main/resources/static/js/app/users.js
> +                                $('#my_table').append(
We want to use *Mustache* or *Handlebars* to generate such templates. We don't want to mix presentation and ui logic together

2019-06-26 06:00 UTC, inventorsoft-academy commented on src/main/resources/templates/current.html
> +                               $('#my_page').append(
See comment above

2019-06-26 06:00 UTC, inventorsoft-academy commented on src/main/resources/templates/users.html
> +    <title>Thymeleaf</title>
Please, change title according to page name

2019-06-26 06:00 UTC, inventorsoft-academy commented on src/main/resources/templates/users.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
Try to avoid using external links, for things that can be preloaded: store this jquery locally on the server as you do for bootstrap

2019-06-26 06:00 UTC, inventorsoft-academy commented on src/main/resources/templates/users.html
> +                    <datalist id="status_list">
Let's load those options from backend

2019-06-26 09:31 UTC, Fedia23 commented on src/main/resources/templates/users.html
> +    <title>Thymeleaf</title>
Ok)

2019-06-26 09:31 UTC, Fedia23 commented on src/main/java/com/geekschool/service/UserService.java
> +import com.geekschool.constants.Status;
Done

2019-06-26 09:31 UTC, Fedia23 commented on src/main/java/com/geekschool/config/security/ApplicationSecurity.java
> +                    .csrf().disable();
I changed

2019-06-26 09:32 UTC, Fedia23 commented on src/main/java/com/geekschool/controllers/UserController.java
> +        UserMapper userMapper = new UserMapper(user);
Good idea, thanks

2019-06-26 09:32 UTC, Fedia23 commented on src/main/java/com/geekschool/mapper/MessageMapper.java
> +public class MessageMapper {
Done

2019-06-26 09:32 UTC, Fedia23 commented on src/main/java/com/geekschool/mapper/UserMapper.java
> +public class UserMapper {
Done

2019-06-27 00:51 UTC, Fedia23 commented on src/main/resources/templates/users.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
fix it

2019-06-27 00:51 UTC, Fedia23 commented on src/main/resources/templates/users.html
> +                    <datalist id="status_list">
Ok, done

2019-06-27 00:51 UTC, Fedia23 commented on src/main/resources/static/js/app/users.js
> +                                $('#my_table').append(
Ok, done

2019-06-27 00:51 UTC, Fedia23 commented on src/main/resources/templates/current.html
> +                               $('#my_page').append(
done

2019-07-04 19:12 UTC, inventorsoft-academy approved these changes

2019-07-04 19:12 UTC, merged